# Site settings
title: "JL Recrutement"
description: "JL Recrutement est un cabinet de recrutement indépendant IT spécialisé sur la technologie PHP."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.jlrecrutement.com" # the base hostname & protocol for your site
sass:
  style: :compressed

# Build settings
markdown: kramdown
port: 8000

# Infos
email: "jeanne@jlrecrutement.com"
tel: "+33649356430"

# Google Analytics
ga_id: UA-54920793-1
